version: '3'
services:
    decoder:
        image: webmonkey/dump1090
        command: dump1090 --net --quiet --no-fix
        devices:
            - "/dev/bus/usb:/dev/bus/usb"
        networks:
            - adsb
        restart: always
    frontend:
        image: webmonkey/dump1090-frontend 
        depends_on:
            - decoder
        ports:
            - 8080:80
        networks:
            - adsb
        restart: always
    fr24feed:
        image: webmonkey/fr24feed
        depends_on:
            - decoder
        volumes:
            - fr24_config:/etc/fr24feed
        networks:
            - adsb
        ports:
            - 8754:8754
        restart: always
    adsbexchange:
        image: ghcr.io/sdr-enthusiasts/docker-adsbexchange:latest
        depends_on:
            - decoder
        networks:
            - adsb
        restart: always
        tty: true
        environment:
            - BEASTHOST=decoder
            - TZ=Europe/London
            - LAT=51.27931344
            - LONG=-0.09005249
            - ALT=203m
            - SITENAME=The_Nest
            - UUID=72ba73a2-17e5-413d-b2af-b648e7d6e531
        tmpfs:
            - /run:rw,nosuid,nodev,exec,relatime,size=64M,uid=1000,gid=1000
    flightaware:
        image: webmonkey/piaware
        depends_on:
            - decoder
        volumes:
            - fa_cache:/var/cache/piaware
        networks:
            - adsb
        restart: always
    planefinder:
        image: webmonkey/planefinder
        depends_on:
            - decoder
        volumes:
            - pfclient_config:/etc/pfclient
        networks:
            - adsb
        ports:
            - 30053:30053
        restart: always

networks:
    adsb:

volumes:
    fa_cache:
    fr24_config:
    pfclient_config:
